import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));

test("US and Iran tracks bind V -> VM; the whole chart is not a single button", () => {
  const board = readFileSync(join(dir, "map-board.tsx"), "utf8");
  const play = readFileSync(join(dir, "play-page.tsx"), "utf8");
  const briefing = readFileSync(join(dir, "briefing.tsx"), "utf8");
  const iran = readFileSync(join(dir, "iran-board.tsx"), "utf8");
  const outcome = readFileSync(join(dir, "outcome-dialog.tsx"), "utf8");
  assert.match(play, /onOmani=/);
  assert.match(play, /onIran=/);
  assert.match(play, /onBoardAct=/);
  assert.match(play, /session\.omani\(\)/);
  assert.match(play, /session\.toll\(\)/);
  assert.match(play, /session\.wait\(\)/);
  assert.match(play, /session\.setPolicy/);
  assert.match(play, /OutcomeDialog/);
  assert.match(play, /ScoreDialog/);
  assert.match(play, /COPY\.booksIdle/);
  assert.match(play, /labels\.idleWhy/);
  assert.match(play, /labels\.omaniShot/);
  assert.match(board, /COPY\.chartLoading/);
  assert.match(play, /COPY\.scoreReplay/);
  assert.match(play, /COPY\.booksBonus/);
  assert.match(play, /COPY\.mineKill/);
  assert.match(play, /COPY\.policyBuy/);
  assert.match(play, /doorsOpen=\{labels\.doorsOpen\}/);
  assert.match(play, /labels\.houseName/);
  assert.match(play, /COPY\.booksLeft/);
  assert.match(board, /onOmani: \(\) => void/);
  assert.match(board, /doorsOpen: boolean/);
  assert.match(board, /canAct=\{doorsOpen\}/);
  assert.doesNotMatch(play, /Onassis/);
  assert.doesNotMatch(play, /The Wire/);
  assert.doesNotMatch(briefing, /Onassis/);
  assert.doesNotMatch(briefing, /The Wire/);
  assert.match(briefing, /Greece, Inc/);
  assert.match(play, /max-w-7xl/);
  assert.match(play, /lg:grid-cols-2/);
  assert.doesNotMatch(play, /lg:grid-cols-3/);
  assert.match(play, /COPY\.sittingTitle/);
  assert.match(play, /COPY\.accountant/);
  assert.doesNotMatch(play, />\s*Fuses\s*</);
  assert.match(board, /onIran: \(\) => void/);
  assert.match(board, /onBoardAct: \(\) => void/);
  assert.match(board, /function CorridorHit/);
  assert.match(board, /COPY\.clickOmani/);
  assert.match(board, /COPY\.clickIran/);
  assert.match(board, /strokeWidth=\{96\}/);
  assert.match(board, /lat=\{26\.82\}/);
  assert.match(board, /clipPath="url\(#deep-water-clip\)"/);
  assert.match(board, /DEEP_WATER/);
  assert.match(board, /recommended !== "none"/);
  assert.doesNotMatch(board, /absolute inset-0 z-10/);
  assert.doesNotMatch(board, /You do not draw a track/);
  assert.doesNotMatch(briefing, /not a plotted track/i);
  assert.doesNotMatch(briefing, /draw a track/i);
  assert.match(play, /COPY\.tabIran/);
  assert.match(play, /COPY\.tabStrait/);
  assert.match(play, /IranBoard/);
  assert.match(play, /session\.usSweep/);
  assert.match(play, /session\.usStrike/);
  assert.match(play, /session\.iranLay/);
  assert.match(play, /session\.iranSurge/);
  assert.match(play, /session\.iranHold/);
  assert.match(play, /COPY\.iranLay/);
  assert.match(play, /iranSeat/);
  assert.match(play, /COPY\.scenarioAsk/);
  assert.match(play, /setBoard\("strait"\)/);
  assert.match(play, /leaveAsk/);
  assert.match(play, /requestStrike/);
  assert.match(play, /COPY\.leaveKeep/);
  assert.match(play, /leaveHoleLine/);
  assert.match(iran, /STRIKE_NODES/);
  assert.match(iran, /onOpenStrait/);
  assert.match(iran, /clickToStrike/);
  assert.match(iran, /n\.emoji/);
  assert.match(iran, /role="tooltip"/);
  assert.match(iran, /onPointerEnter/);
  assert.match(iran, /dumpedHoles/);
  assert.match(iran, /COPY\.holeDumpedMark/);
  assert.match(iran, /leaveHoleLine/);
  assert.match(play, /n\.emoji/);
  assert.match(play, /clickToStrike/);
  assert.match(play, /spider=\{labels\.spiderHoles\.length > 0\}/);
  assert.match(outcome, /COPY\.outcomeGoStrikes/);
  assert.match(outcome, /COPY\.outcomeGoStrait/);
  assert.match(outcome, /grid-cols-2/);
  assert.doesNotMatch(iran, /STRIKE\.ideal/);
  assert.doesNotMatch(play, /STRIKE\.ideal/);
  assert.doesNotMatch(iran, /sm:grid-cols-3/);
});

test("price meter stays a meter; mine circles carry mines est", () => {
  const board = readFileSync(join(dir, "map-board.tsx"), "utf8");
  assert.match(board, /function PriceOverlay/);
  assert.match(board, /function MineTip/);
  assert.match(board, /fogTip/);
  assert.match(board, /pickMine/);
  assert.match(board, /onPointerMove/);
  assert.match(board, /role="tooltip"/);
  assert.doesNotMatch(board, /function MineHit/);
  assert.doesNotMatch(board, /COPY\.notLive/);
  assert.doesNotMatch(board, /grid-cols-5/);
  assert.doesNotMatch(board, /PriceComponents/);
  assert.doesNotMatch(board, /live EIA/);
});
