/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as ReceiptsRouteImport } from './routes/receipts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/briefing': typeof BriefingRoute
  '/receipts': typeof ReceiptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/briefing': typeof BriefingRoute
  '/receipts': typeof ReceiptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/briefing': typeof BriefingRoute
  '/receipts': typeof ReceiptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/architecture' | '/briefing' | '/receipts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architecture' | '/briefing' | '/receipts'
  id: '__root__' | '/' | '/architecture' | '/briefing' | '/receipts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BriefingRoute: typeof BriefingRoute
  ReceiptsRoute: typeof ReceiptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BriefingRoute: BriefingRoute,
  ReceiptsRoute: ReceiptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
